#!/bin/bash

# Function to retrieve the owners, CIDR, country, provider, and email of an IP address
get_ip_info() {
  local ip=$1
  local owners=""
  local cidr=()
  local country=()
  local provider=""
  local emails=()

  if [[ $ip =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    # Check if the IP address belongs to RIPE (European) registry
    local response=$(whois -h whois.ripe.net "$ip")

    if ! grep -q "IPv4 address block not managed by the RIPE NCC" <<< "$response"; then
      provider="RIPE"
      while read -r line; do
        if [[ $line =~ ^descr: ]]; then
          owners+=$(awk -F ':' '{print $2}' <<< "$line" | tr -s ' ' | tr '\n' '/')
        elif [[ $line =~ ^inetnum: ]]; then
          cidr+=($(awk -F ': ' '{print $2}' <<< "$line" | awk '{print $1}'))
        elif [[ $line =~ ^country: ]]; then
          country+=($(awk -F ': ' '{print $2}' <<< "$line"))
        elif [[ $line =~ @ ]]; then
          emails+=($(grep -oE '[[:alnum:]._-]+@[[:alnum:]._-]+\.[[:alnum:]]+' <<< "$line"))
        fi
      done <<< "$response"
    else
      # Check if the IP address belongs to ARIN (American) registry
      local response=$(whois -h whois.arin.net "$ip")

      provider="ARIN"
      while read -r line; do
        if [[ $line =~ ^OrgName: ]]; then
          owners+=$(awk -F ':' '{print $2}' <<< "$line" | tr -s ' ' | tr '\n' '/')
        elif [[ $line =~ ^CIDR: ]]; then
          cidr+=($(awk -F ': ' '{print $2}' <<< "$line"))
        elif [[ $line =~ ^Country: ]]; then
          country+=($(awk -F ': ' '{print $2}' <<< "$line"))
        elif [[ $line =~ ^OrgAbuseEmail: ]]; then
          emails+=($(awk -F ': ' '{print $2}' <<< "$line"))
        fi
      done <<< "$response"
    fi
  fi

  # Remove the trailing slash from owners string
  owners=${owners%/}

  printf "IP: \033[1;33m%-15s\033[0m Owners: \033[1;36m%-40s\033[0m Provider: \033[1;34m%s\033[0m\n" "$ip" "$owners" "$provider"
  for ((i=0; i<${#cidr[@]}; i++)); do
    printf "   CIDR: \033[1;35m%-18s\033[0m Country: \033[1;32m%s\033[0m\n" "${cidr[$i]}" "${country[$i]}"
  done

  if [[ ${#emails[@]} -gt 0 ]]; then
    printf "   Emails:\n"
    for ((i=0; i<${#emails[@]}; i++)); do
      printf "      \033[1;31m%s\033[0m\n" "${emails[$i]}"
    done
  fi
}

# Read from standard input and determine the owners, CIDR, country, provider, and email of each IP address
while IFS= read -r ip || [[ -n "$ip" ]]; do
  info=$(get_ip_info "$ip")
  echo "$info"
done

