#!/bin/bash

# Function to retrieve the owners, CIDR, country, provider, and email of an IP address
get_ip_info() {
  local ip=$1
  local owners=""
  local cidr=()
  local country=()
  local provider=""
  local emails=()

 # if [[ $ip =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    local response=$(whois "$ip")

    if grep -q "RIPE" <<< "$response"; then
      provider="RIPE"
    elif grep -q "ARIN" <<< "$response"; then
      provider="ARIN"
    elif grep -q "APNIC" <<< "$response"; then
      provider="APNIC"
    elif grep -q "LACNIC" <<< "$response"; then
      provider="LACNIC"
    elif grep -q "AFRINIC" <<< "$response"; then
      provider="AFRINIC"
    fi

    while read -r line; do
      if [[ $line =~ ^descr:|^OrgName:|^owner: ]]; then
        owners+=$(awk -F ':' '{print $2}' <<< "$line" | tr -s ' ' | tr '\n' '/')
      elif [[ $line =~ ^route:|^CIDR: ]]; then
        cidr+=($(awk -F ': ' '{print $2}' <<< "$line"))
      elif [[ $line =~ ^country:|^Country: ]]; then
        country+=($(awk -F ': ' '{print $2}' <<< "$line"))
      elif [[ $line =~ @ ]]; then
        email=$(grep -oE '[[:alnum:]._-]+@[[:alnum:]._-]+\.[[:alnum:]]+' <<< "$line")
        if ! [[ " ${emails[@]} " =~ " ${email} " ]]; then
          emails+=("$email")
        fi
      fi
    done <<< "$response"
  #fi

  owners=${owners%/}

  printf "IP: \033[1;33m%-15s\033[0m Owners: \033[1;36m%-40s\033[0m Provider: \033[1;34m%s\033[0m\n" "$ip" "$owners" "$provider"
  for ((i=0; i<${#cidr[@]}; i++)); do
    printf "   CIDR: \033[1;35m%-18s\033[0m Country: \033[1;32m%s\033[0m\n" "${cidr[$i]}" "${country[$i]}"
  done

  if [[ ${#emails[@]} -gt 0 ]]; then
    printf "   Emails:\n"
    for ((i=0; i<${#emails[@]}; i++)); do
      printf "      \033[1;31m%s\033[0m\n" "${emails[$i]}"
    done
  fi
}

while IFS= read -r ip || [[ -n "$ip" ]]; do
  info=$(get_ip_info "$ip")
  echo "$info"
done
